version: '3.7'
services:
  client:
    image: node:16
    container_name: container_react
    restart: always
    ports:
      - 3000:3000
    volumes:
      - '.:/app'
    working_dir: /app
    command: bash -c "npm install && npm start"